Added FullPath to File for Zips.
mholt/archiver pull request #215
Opened 2020-02-23 15:19 UTC by J7mbo

Hi @mholt, saw that you're busy with Caddy, all good I'll use my fork for a while. 

Related to #130.

When you have time, can this be considered? There's a lot missing, the `File` is used everywhere and I only needed it when walking around a Zip, but perhaps we can discuss making this work for everything and get the PR in.

2021-01-19 10:34 UTC, J7mbo commented
If this isn't going anywhere I will close.

2021-01-19 17:53 UTC, mholt requested changes
Thanks, sorry for the delay.

2021-01-19 17:53 UTC, mholt commented on archiver.go
> +	FullPath string
Would be useful to provide a comment here explaining what the field should contain.

2022-01-02 09:43 UTC, mholt commented
I think this is implemented in #302, as NameInArchive, if I understand correctly.

2022-01-02 09:43 UTC, closed without merging

2022-01-02 09:51 UTC, J7mbo commented
All good, I didn't put too much effort into it. Good luck in 2022! 👋