Fix nested directory listing for archives without explicit directory names.
mholt/archiver pull request #339
Opened 2022-06-15 07:58 UTC by jeremyje

Fixes #338 

This PR fixes 2 issues:
* Listing dot-prefixed directories had their '.' stripped.
* Directory listing for nested directories were ignored.

This change adds some tests around this area.

2022-06-15 21:15 UTC, mholt requested changes
This is great, thanks so much for the added tests and the bug fixes. Just a couple questions/requests.

2022-06-16 03:26 UTC, jeremyje commented on .gitignore
> +__debug_bin
Delve while running in vscode

2022-06-16 03:27 UTC, jeremyje commented on fs_test.go
> +				wantLS := wantLS
Yes. This is important when you run via `t.Parallel()`.

2022-06-16 07:18 UTC, jeremyje commented on fs_test.go
> +	"github.com/google/go-cmp/cmp"
Removed the dependency.

2022-06-16 18:46 UTC, merged